#############################################################################
# Makefile for building: GEDIG_A2.app/Contents/MacOS/GEDIG_A2
# Generated by qmake (2.01a) (Qt 4.7.3) on: Tue Oct 2 14:40:03 2012
# Project:  GEDIG_A2.pro
# Template: app
# Command: /Applications/QtSDK/Desktop/Qt/473/gcc/bin/qmake -spec /Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile GEDIG_A2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -I. -I/Applications/QtSDK/Desktop/Qt/473/gcc/lib/QtCore.framework/Versions/4/Headers -I/Applications/QtSDK/Desktop/Qt/473/gcc/include/QtCore -I/Applications/QtSDK/Desktop/Qt/473/gcc/lib/QtGui.framework/Versions/4/Headers -I/Applications/QtSDK/Desktop/Qt/473/gcc/include/QtGui -I/Applications/QtSDK/Desktop/Qt/473/gcc/lib/QtOpenGL.framework/Versions/4/Headers -I/Applications/QtSDK/Desktop/Qt/473/gcc/include/QtOpenGL -I/Applications/QtSDK/Desktop/Qt/473/gcc/include -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -F/Applications/QtSDK/Desktop/Qt/473/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Applications/QtSDK/Desktop/Qt/473/gcc/lib -L/Applications/QtSDK/Desktop/Qt/473/gcc/lib -framework QtOpenGL -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Applications/QtSDK/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/opengl.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		GEDIG_A2.pro
QMAKE_TARGET  = GEDIG_A2
DESTDIR       = 
TARGET        = GEDIG_A2.app/Contents/MacOS/GEDIG_A2

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile GEDIG_A2.app/Contents/PkgInfo GEDIG_A2.app/Contents/Resources/empty.lproj GEDIG_A2.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) GEDIG_A2.app/Contents/MacOS/ || $(MKDIR) GEDIG_A2.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GEDIG_A2.pro  /Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++/qmake.conf /Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/opengl.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile GEDIG_A2.pro
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/opengl.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
/Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile GEDIG_A2.pro

GEDIG_A2.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) GEDIG_A2.app/Contents || $(MKDIR) GEDIG_A2.app/Contents 
	@$(DEL_FILE) GEDIG_A2.app/Contents/PkgInfo
	@echo "APPL????" >GEDIG_A2.app/Contents/PkgInfo
GEDIG_A2.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) GEDIG_A2.app/Contents/Resources || $(MKDIR) GEDIG_A2.app/Contents/Resources 
	@touch GEDIG_A2.app/Contents/Resources/empty.lproj
	
GEDIG_A2.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) GEDIG_A2.app/Contents || $(MKDIR) GEDIG_A2.app/Contents 
	@$(DEL_FILE) GEDIG_A2.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,GEDIG_A2,g" -e "s,@TYPEINFO@,????,g" /Applications/QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++/Info.plist.app >GEDIG_A2.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/GEDIG_A21.0.0 || $(MKDIR) .tmp/GEDIG_A21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GEDIG_A21.0.0/ && $(COPY_FILE) --parents mainwindow.h mainwindow.h .tmp/GEDIG_A21.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp .tmp/GEDIG_A21.0.0/ && (cd `dirname .tmp/GEDIG_A21.0.0` && $(TAR) GEDIG_A21.0.0.tar GEDIG_A21.0.0 && $(COMPRESS) GEDIG_A21.0.0.tar) && $(MOVE) `dirname .tmp/GEDIG_A21.0.0`/GEDIG_A21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GEDIG_A21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r GEDIG_A2.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/Applications/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_mainwindow.cpp: mainwindow.h
	/Applications/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

